#!/usr/bin/env node
const fs = require('fs')
const manifestPath = './extension/manifest.json'
var manifest = require(`.${manifestPath}`)
const firefoxManifest = require('../extension/firefox.manifest.json')

const json = JSON.stringify(Object.assign(manifest, firefoxManifest), null, 2)
fs.writeFile(manifestPath, json, (err, res) => {
  if (err) {
    console.log('err', err)
    process.exit(1)
  } else {
    process.exit(0)
  }
})
