#!/usr/bin/env sh
echo "compare packages"
folder=/tmp/compare_packages

unzip_in_new_folder(){
  # source: http://stackoverflow.com/a/8107983/3324977
  ls *.zip|awk -F'.zip' '{print "unzip "$0" -d "$1".folder"}'|sh
}

rm -rf $folder
cp -r packages $folder
cd $folder
unzip_in_new_folder
for f in *.folder ; do echo "\n$f" && du -sh $f/**/* ; done
