#!/usr/bin/env sh
version=$(cat package.json |jd version)
cp extension/manifest.json ./manifest.backup.json

# build chrome package
cd extension
zip -r ../packages/time-capsule.$version.chrome.zip .

# build firefox package
cd ..
./scripts/build-firefox-manifest
cd extension
zip -r ../packages/time-capsule.$version.firefox.zip .
cd ..
mv ./manifest.backup.json extension/manifest.json
