#!/usr/bin/env bash

set -eu

# Expects extension/manifest.json version to have been incremented, by running `npm version <level>`,
# which would have triggered scripts/postversion
version=$(jq '.version' -r < extension/manifest.json)

npm run lint
npm run build
git push origin main
git push --tags

cd extension
# Remove previous build if any
rm -f "time-capsule.$version.zip" "time-capsule.chrome.$version.zip" "time-capsule.firefox.$version.zip"

cp ./manifest.json ../manifest.json.bak
cp ./popup/popup.html ../popup.html.bak
cp ./settings/settings.html ../settings.html.bak

# Firefox
sed -i 's/open-periodicity-menu/_execute_browser_action/' ./manifest.json
zip -r "../packages/time-capsule.firefox.$version.zip" .

# Chrome
cp ../node_modules/webextension-polyfill/dist/browser-polyfill.min.js .
cat ../manifest.json.bak |
  jq '.background.scripts = [ "browser-polyfill.min.js" ] + .background.scripts' |
  jq '.permissions = .permissions - [ "menus" ]' |
  jq 'del(.browser_specific_settings)' > ./manifest.json
sed -i '/popup.js/i <script src="../browser-polyfill.min.js"></script>' ./popup/popup.html
sed -i '/settings.js/i <script src="../browser-polyfill.min.js"></script>' ./settings/settings.html
zip -r "../packages/time-capsule.chrome.$version.zip" .

# Cleanup
mv ../manifest.json.bak ./manifest.json
mv ../popup.html.bak ./popup/popup.html
mv ../settings.html.bak ./settings/settings.html
rm ./browser-polyfill.min.js

cd ..

sleep 2

wget "https://github.com/maxlath/time-capsule/archive/refs/tags/v${version}.zip" --output-document "./github-artifacts/v${version}.zip"

echo "Now you would need to upload packages/time-capsule.firefox.$version.zip
to https://addons.mozilla.org/fr/developers/addon/time-capsule/versions/submit/"
echo "It will also ask you for the source code: you can then upload ./github-artifacts/v${version}.zip"
